apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"drkiq"},"name":"drkiq","namespace":"default"},"spec":{"replicas":1,"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"drkiq"}},"spec":{"containers":[{"env":[{"name":"CACHE_URL","value":"redis://redis:6379/0"},{"name":"DATABASE_URL","value":"postgresql://drkiq:yourpassword@postgres:5432/drkiq?encoding=utf8\u0026pool=5\u0026timeout=5000"},{"name":"JOB_WORKER_URL","value":"redis://redis:6379/0"},{"name":"LISTEN_ON","value":"0.0.0.0:8000"},{"name":"SECRET_TOKEN","value":"a9c4853412c560983a37308a54c7164ea77c9b8c47d48b13d59c759d27ee07380e0521b4a480ada9f5de5451679332c23c27ec68dd8967b477f658c04a14c198"},{"name":"WORKER_PROCESSES","value":"1"}],"image":"10.0.0.12:5000/drkiq","name":"drkiq","ports":[{"containerPort":8000}],"resources":{},"volumeMounts":[{"mountPath":"/drkiq","name":"drkiq-claim0"}]}],"restartPolicy":"Always","volumes":[{"name":"drkiq-claim0","persistentVolumeClaim":{"claimName":"drkiq-claim0"}}]}}},"status":{}}
  creationTimestamp: 2017-08-15T21:53:18Z
  generation: 14
  labels:
    app: drkiq
  name: drkiq
  namespace: default
  resourceVersion: "152074"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/drkiq
  uid: 25bc9f0c-8204-11e7-9538-08002769efd5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drkiq
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drkiq
    spec:
      containers:
      - env:
        - name: CACHE_URL
          value: redis://10.0.0.42:6379/0
        - name: DATABASE_URL
          value: postgresql://drkiq:yourpassword@10.0.0.9:5432/drkiq?encoding=utf8&pool=5&timeout=5000
        - name: JOB_WORKER_URL
          value: redis://10.0.0.42:6379/0
        - name: LISTEN_ON
          value: 0.0.0.0:8000
        - name: SECRET_TOKEN
          value: a9c4853412c560983a37308a54c7164ea77c9b8c47d48b13d59c759d27ee07380e0521b4a480ada9f5de5451679332c23c27ec68dd8967b477f658c04a14c198
        - name: WORKER_PROCESSES
          value: "1"

        image: 10.0.0.12:5000/drkiq
        imagePullPolicy: Always
        name: drkiq
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-08-17T20:54:01Z
    lastUpdateTime: 2017-08-17T20:54:01Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 14
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
