apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"redis"},"name":"redis","namespace":"default"},"spec":{"replicas":1,"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"redis"}},"spec":{"containers":[{"image":"redis:3.0.5","name":"redis","ports":[{"containerPort":6379}],"resources":{},"volumeMounts":[{"mountPath":"/var/lib/redis/data","name":"drkiq-redis"}]}],"restartPolicy":"Always","volumes":[{"name":"drkiq-redis","persistentVolumeClaim":{"claimName":"drkiq-redis"}}]}}},"status":{}}
  creationTimestamp: 2017-08-14T20:41:40Z
  generation: 1
  labels:
    app: redis
  name: redis
  namespace: default
  resourceVersion: "151037"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/redis
  uid: f98272c5-8130-11e7-aa70-08002769efd5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - image: redis:3.0.5
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/redis/data
          name: drkiq-redis
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: drkiq-redis
        persistentVolumeClaim:
          claimName: drkiq-redis
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-08-17T20:45:21Z
    lastUpdateTime: 2017-08-17T20:45:21Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
