apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"registry"},"name":"registry","namespace":"default"},"spec":{"replicas":1,"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"registry"}},"spec":{"containers":[{"image":"registry:2.6.1","imagePullPolicy":"IfNotPresent","name":"registry","ports":[{"containerPort":5000,"protocol":"TCP"}]}]}}}}
  creationTimestamp: 2017-08-15T06:55:26Z
  generation: 1
  labels:
    app: registry
  name: registry
  namespace: default
  resourceVersion: "151054"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/registry
  uid: b7858c88-8186-11e7-87b5-08002769efd5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: registry
    spec:
      containers:
      - image: registry:2.6.1
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-08-17T20:45:25Z
    lastUpdateTime: 2017-08-17T20:45:25Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
