apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-08-15T21:55:03Z
  labels:
    app: drkiq
  name: drkiq
  namespace: default
  resourceVersion: "35127"
  selfLink: /api/v1/namespaces/default/services/drkiq
  uid: 64a32215-8204-11e7-9538-08002769efd5
spec:
  clusterIP: 10.0.0.250
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31865
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: drkiq
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
