apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-08-17T19:14:43Z
  labels:
    app: postgrres
  name: postgres
  namespace: default
  resourceVersion: "143351"
  selfLink: /api/v1/namespaces/default/services/postgres
  uid: 531f8d8d-8380-11e7-9d73-08002769efd5
spec:
  clusterIP: 10.0.0.9
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
