apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"redis"},"name":"redis","namespace":"default"},"spec":{"ports":[{"name":"6379","port":6379,"targetPort":6379}],"selector":{"app":"redis"}},"status":{"loadBalancer":{}}}
  creationTimestamp: 2017-08-14T20:41:43Z
  labels:
    app: redis
  name: redis
  namespace: default
  resourceVersion: "13455"
  selfLink: /api/v1/namespaces/default/services/redis
  uid: fbb907d8-8130-11e7-aa70-08002769efd5
spec:
  clusterIP: 10.0.0.42
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
